### ISSUE TITLE
Could not find a declaration file for module 'manakin'

### ISSUE THREAD

**Issue by fu-hsi** [vitaly-t/manakin#4]
Editor hint for:
`const con = require('manakin').global;`

> Could not find a declaration file for module 'manakin'. 'c:/xampp/htdocs/Topin/node_modules/manakin/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/manakin` if it exists or add a new declaration (.d.ts) file containing `declare module 'manakin';`ts(7016)

`npm install @types/manakin`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fmanakin - Not found
npm ERR! 404
npm ERR! 404  '@types/manakin@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mariu\AppData\Roaming\npm-cache\_logs\2019-10-19T19_05_47_304Z-debug.log
```
Module works.

**Comment by vitaly-t** [comment]
This module does not have any TypeScript declarations.

At this point I'm not sure I will be spending time on further development of this, because of #2. Since Node.js v12 over-complicated the color output, I'm not sure I can fix it.
